core/urls.py
from django.urls import path
from .views import ClienteListView, ClienteDetailView, ClienteCreateView, ClienteUpdateView, ClienteDeleteView
from .views import FunciUpdateView, CompraCreateView, CompraDetailView, CompraDeleteView
from .views import ProdutoCreateView, ProdutoDeleteView, ProdutoUpdateView
from .views import registro_funcionario, login_funcionario

urlpatterns = [
    #login e cadastro para logar, é para o funcionario.
    path('login/', login_funcionario, name='login'),
    path('registro/', registro_funcionario, name='registro'),
    
    #Página home
    path('', ClienteListView.as_view(), name='cliente'),

    #Editaveis do funcionario sobre a tabela Cliente
    path('clientes/<str:pk>', ClienteDetailView.as_view(), name="cliente-detalhe"),
    path('clientes/novo/', ClienteCreateView.as_view(), name="cliente-criar"),
    path('clientes/<str:pk>/atualiza/', ClienteUpdateView.as_view(), name="cliente-atualiza"),
    path('clientes/<str:pk>/apaga', ClienteDeleteView.as_view(), name= "cliente-apaga"),
    
    #Editar dados funcionario
    path('funcionarios/<str:pk>/atualiza/', FunciUpdateView.as_view(), name= "funcionario-atualiza"),

    #Editaveis do funcionario sobre a tabela Compra
    path('compra/nova/', CompraCreateView.as_view(), name='compra-nova'),
    path('compra/<int:pk>/', CompraDetailView.as_view(), name='compra-detalhe'),
    path('compra/<int:pk>/apaga', CompraDeleteView.as_view(), name='compra-apaga'),

    #Editaveis do funcionario sobre a tabela Produto
    path('produto/novo/', ProdutoCreateView.as_view(), name='produto-novo'),
    path('produto/<int:pk>/apaga', ProdutoDeleteView.as_view(), name= "produto-apaga"),
    path('produto/<int:pk>/atualiza/', ProdutoUpdateView.as_view(), name="produto-atualiza"),
]

madeireira/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('django.contrib.auth.urls')),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User

class Funcionario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cpf = models.CharField(max_length=11, unique=True)
    nome = models.CharField(max_length=100)
    idade = models.IntegerField()
    numero = models.CharField(max_length=15)
    email = models.EmailField()

    def __str__(self):
        return self.nome


class Cliente(models.Model):
    cpf = models.CharField(max_length=11, primary_key=True)
    nome = models.CharField(max_length=100)
    numero = models.CharField(max_length=15, blank=True, null=True)
    
    def __str__(self):
        return self.nome

class Produto(models.Model):
    id = models.AutoField(primary_key=True)
    nome_produto = models.CharField(max_length=100)
    valor = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.nome_produto
    
class Compra(models.Model):
    cod = models.AutoField(primary_key=True)
    funcionario = models.ForeignKey(Funcionario, on_delete=models.CASCADE)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    produtos = models.ManyToManyField(Produto, through='ItemCompra')
    valor_total_dos_produtos = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    data = models.DateTimeField(auto_now=True)

    def calcular_valor_total(self):
        total = 0
        for item in self.itemcompra_set.all():
            total += item.produto.valor * item.quantidade
        self.valor_total_dos_produtos = total
        self.save(update_fields=['valor_total_dos_produtos'])

    def __str__(self):
        return f'Compra #{self.cod} - Cliente: {self.cliente.nome}'

class ItemCompra(models.Model):
    compra = models.ForeignKey(Compra, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField()

    def subtotal(self):
        return self.produto.valor * self.quantidade

core/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Funcionario
from django.forms import inlineformset_factory
from .models import Compra, ItemCompra

class FuncionarioRegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = Funcionario
        fields = ['cpf', 'nome', 'idade', 'numero', 'email']

    def save(self, commit=True):
        funcionario = super().save(commit=False)
        user = User.objects.create_user(
            username=self.cleaned_data['cpf'],
            password=self.cleaned_data['password']
        )
        funcionario.user = user
        if commit:
            user.save()
            funcionario.save()
        return funcionario
    
    
class CompraForm(forms.ModelForm):
    class Meta:
        model = Compra
        fields = ['cliente']

ItemCompraFormSet = inlineformset_factory(
    Compra,
    ItemCompra,
    fields=('produto', 'quantidade'),
    extra=10,
    can_delete=False
)

core/views.py
from django.http import HttpResponse
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Cliente, Funcionario, Compra, Produto
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .forms import FuncionarioRegisterForm, CompraForm, ItemCompraFormSet
from .models import Funcionario

def sua_view(request):
    data_inicio = request.GET.get('data_inicio')
    data_fim = request.GET.get('data_fim')
    compras = Compra.objects.all()

    if data_inicio and data_fim:
        compras = compras.filter(data__range=[data_inicio, data_fim])

    context = {
        'compras': compras,
    }
    return render(request, 'home.html', context)

def registro_funcionario(request):
    if request.method == 'POST':
        form = FuncionarioRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = FuncionarioRegisterForm()
    return render(request, 'registros/registro.html', {'form': form})

def login_funcionario(request):
    erro = ''
    if request.method == 'POST':
        cpf = request.POST['cpf']
        senha = request.POST['senha']
        user = authenticate(username=cpf, password=senha)
        if user:
            login(request, user)
            return redirect('cliente')
        else:
            erro = 'CPF ou senha inválidos.'
    return render(request, 'registros/login.html', {'erro': erro})
# Funcionalidades da tabela Cliente

from django.core.paginator import Paginator

class ClienteListView(LoginRequiredMixin, ListView):
    model = Cliente
    template_name = 'home.html'
    context_object_name = 'clientes'
    paginate_by = 4
    
    def get_queryset(self):
        queryset = super().get_queryset()
        termo_busca = self.request.GET.get('buscar_cliente', '')
        if termo_busca:
            queryset = queryset.filter(nome__icontains=termo_busca)
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        funcionario_logado = self.request.user.funcionario
        context['funcionario_logado'] = funcionario_logado

        compras = Compra.objects.filter(funcionario=funcionario_logado)
        termo_produto = self.request.GET.get('buscar_produto', '')

        produtos = Produto.objects.all()
        if termo_produto:
            produtos = produtos.filter(nome_produto__icontains=termo_produto)

        compras_paginator = Paginator(compras, 2)
        produtos_paginator = Paginator(produtos, 4)

        compra_page_number = self.request.GET.get('compras_page')
        produto_page_number = self.request.GET.get('produtos_page')

        context['compras'] = compras_paginator.get_page(compra_page_number)
        context['produtos'] = produtos_paginator.get_page(produto_page_number)

        # Para manter o valor no campo busca do template
        context['buscar_produto'] = termo_produto

        return context


class ClienteDetailView(LoginRequiredMixin,DetailView):
    model = Cliente
    template_name = "cliente/detalhes_cliente.html"

class ClienteCreateView(LoginRequiredMixin, CreateView):
    model = Cliente
    fields = ['cpf', 'nome', 'numero']
    template_name = "cliente/cliente.html"
    success_url = reverse_lazy('cliente')
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class ClienteUpdateView(LoginRequiredMixin, UpdateView):
    model = Cliente
    fields = ['cpf', 'nome', 'numero']
    template_name = "cliente/atualiza_cliente.html"
    success_url = reverse_lazy('cliente')
    
class ClienteDeleteView(LoginRequiredMixin, DeleteView):
    model = Cliente
    template_name = "cliente/apagar.html"
    success_url = reverse_lazy('cliente')

# Funcionalidades da tabela Funcionario

class FunciUpdateView(LoginRequiredMixin, UpdateView):
    model = Funcionario
    fields = ['cpf', 'nome','idade', 'numero','email']
    template_name = "funcionario/atualiza_funci.html"
    success_url = reverse_lazy('cliente')

# Funcionalidades da tabela Produto

class ProdutoCreateView(LoginRequiredMixin, CreateView):
    model = Produto
    fields = ['nome_produto', 'valor']
    template_name = "produto/produto_novo.html"
    success_url = reverse_lazy('cliente')
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
class ProdutoUpdateView(LoginRequiredMixin, UpdateView):
    model = Produto
    fields = ['nome_produto','valor']
    template_name = "produto/atualiza_produto.html"
    success_url = reverse_lazy('cliente')

class ProdutoDeleteView(LoginRequiredMixin, DeleteView):
    model = Produto
    template_name = "produto/apagar_produto.html"
    success_url = reverse_lazy('cliente')

class CompraCreateView(CreateView):
    model = Compra
    form_class = CompraForm
    template_name = 'compras/compra_form.html'
    success_url = reverse_lazy('cliente')

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data['formset'] = ItemCompraFormSet(self.request.POST)
        else:
            data['formset'] = ItemCompraFormSet()
        return data
    
    def form_valid(self, form):
        form.instance.funcionario = self.request.user.funcionario
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()

            self.object.calcular_valor_total()

            return redirect(self.success_url)
        else:
            return self.render_to_response(self.get_context_data(form=form))

class CompraDetailView(DetailView):
    model = Compra
    template_name = 'compras/compra_detalhes.html'
    context_object_name = 'compra'

class CompraDeleteView(LoginRequiredMixin, DeleteView):
    model = Compra
    template_name = "compras/apagar_compra.html"
    success_url = reverse_lazy('cliente')

core/templates/produto/apagar_produto.html
{% load static %}
<!doctype html>
<html lang="pt-br" data-bs-theme="dark">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Apagar Produto</title>
    <link rel="icon" type="image/png" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
</head>
<body>
    <article class="w-100 h-100 d-flex flex-column align-items-center justify-content-center">
        <div class="bg-success-subtle p-5 border border-2 border-success rounded-2 shadow">
            <h1 class="mb-3 text-center">Deseja mesmo deletar o Produto?</h1>
            <form class="d-flex flex-column" method="post">
                {%csrf_token%}

                <button class="btn btn-success my-3 p-3" type ="submit">Sim, Deletar.</button>
                <a class="btn btn-outline-danger my-3 p-3" href="{%url 'cliente'%}">Não, Cancelar.</a>
            </form>
        </div>
    </article>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
</html>

core/templates/produto/atualiza_produto.html
{% load static %}
<!doctype html>
<html lang="pt-br" data-bs-theme="dark">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Atualizar Produto</title>
    <link rel="icon" type="image/png" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
</head>
<body>
    <article class="w-100 h-100 d-flex flex-column align-items-center justify-content-center">
        <div class="bg-success-subtle p-5 border border-2 border-success rounded-2 shadow">
            <h1 class="mb-3 text-center">Editar Produto</h1>
            <form class="d-flex flex-column" method="post">
                {% csrf_token %}

                <div class="input-group mb-3">
                    <span class="input-group-text"><label for="id_nome_produto">Nome:</label></span>
                    <input type="text" name="nome_produto" id="id_nome_produto" value="{{ form.nome_produto.value|default_if_none:'' }}" class="form-control">
                </div>
            
                <div class="input-group mb-3">
                    <span class="input-group-text"><label for="id_valor">Valor:</label></span>
                    <input type="number" step="0.01" name="valor" id="id_valor" value="{{ form.valor.value|default_if_none:'' }}"class="form-control">
                </div>
            
                <button type="submit" class="btn btn-success my-2">Salvar</button>
                <a class="btn btn-outline-danger my-2" href="{%url 'cliente'%}">Cancelar</a>
            </form>
        </div>
    </article>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
</html>

core/templates/produto/produto_novo.html
{% load static %}
<!doctype html>
<html lang="pt-br" data-bs-theme="dark">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Novo Produto</title>
    <link rel="icon" type="image/png" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
</head>
<body>
    <article class="w-100 h-100 d-flex flex-column align-items-center justify-content-center">
        <div class="bg-success-subtle p-5 border border-2 border-success rounded-2 shadow">
            <h1 class="mb-3 text-center">Adicionar Produto</h1>
            <form class="d-flex flex-column" method="post">
                {% csrf_token %}

                <div class="input-group mb-3">
                    <span class="input-group-text"><label for="id_nome_produto">Nome:</label></span>
                    <input type="text" name="nome_produto" id="id_nome_produto" placeholder="Madeira" class="form-control">
                </div>
            
                <div class="input-group mb-3">
                    <span class="input-group-text"><label for="id_valor">Valor:</label></span>
                    <input type="number" step="0.01" name="valor" id="id_valor" placeholder="10.90" class="form-control">
                </div>
            
                <button class="btn btn-success my-3" type ="submit">Adicionar</button>
                <a class="btn btn-outline-danger my-3" href="{%url 'cliente'%}">Cancelar</a>
            </form>
        </div>
    </article>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
</html>